### ISSUE TITLE
Revisar

### ISSUE THREAD

**Issue by barbosa92** [Jnv821/4Geeks-ConditionalCard#2]
- [x] Revisar que al hacer click en los iconos de las RRSS te lleven al perfil especificado en el input.

**Comment by Jnv821** [comment]
Actua correctamente con el método de funcionamiento pensado. El método de funcionamiento pensado es el siguiente: 

- Si el enlace no es especificado retorna a la página de la carta condicional
- Si el enlace está especificado lleva a dicha dirección especificada. 

Si no deberia funcionar de esta forma, por favor dar directrices de como deberia de funcionar. 

![ConditionalCardWorking](https://user-images.githubusercontent.com/95052283/204378491-572a8302-581c-4eff-a198-2551a7fff9db.gif)

**Comment by Jnv821** [comment]
Hecho. 

La implementación no es la mejor ni se acerca a ella.
"Errores" notables: 
- Es necesario presionar el boton de la red social 2 veces en caso de usar solo el nombre de usuario.
- En caso de dejar el campo de linkedin vacio, llevará a https://www.linkedin.com/in/ página que no existe y tirará un error 404.

Estos errores se podrián solucionar con otra implementacion, como utilizar los casos de la función *constructUrl* dentro de la propia etiqueta <a> y pasarle simplemente el valor del campo de formulario. Aún asi esta implementación deja por fuera otra cantidad de casos y también conlleva sus cosas.
